(Web Embeds) - Can't onboard w/ Bayside Web Embed
ApollosProject/apollos-embeds pull request #29
Opened 2023-04-14 17:52 UTC by linb1

## Basecamp Scope

[(Web Embeds) - Can't onboard w/ Bayside Web Embed](https://3.basecamp.com/3926363/buckets/27088350/card_tables/cards/6040356392)

## What was done?

1. Checking is now based on if the entire profile is completed rather than each individual item
2. Button is now disabled unless every item has been filled out (rather than first and last name only). This should remove partially filled out profiles from now on

## How to test?

2023-04-14 20:01 UTC, jordanwade commented
@linb1 do we have to have that final 'Welcome Back' state of the modal? 
<img width="1039" alt="CleanShot 2023-04-14 at 15 00 46@2x" src="https://user-images.githubusercontent.com/2528817/232143956-952961dc-4589-4a91-9dbd-f800f6ef4244.png">

2023-04-14 20:20 UTC, linb1 commented
@jordanwade No, I don't think it's necessary to have. I figured it didn't make sense to have a person re-input their profile information in order to continue, so I hid all the inputs and have it display the welcome back message instead if they have a profile already. We could have the user be redirected straight to the feature feed after they enter the 6 digit code if they already have an account. WDYT?

2023-04-14 20:21 UTC, jordanwade commented
@linb1 Yes, let's redirect them to the feature feed. If they've authed and we have a profile for them.

2023-04-14 20:56 UTC, jordanwade requested changes
Once you update that welcome screen to just redirect. I think this will be good to go.

2023-04-14 21:04 UTC, linb1 commented
@jordanwade I've made a mistake. It looks like users are already being redirected if we have a profile for them: https://github.com/ApollosProject/apollos-embeds/blob/9ee4bbab47a02f4c01b9329c5fc772700153cb48/src/components/Auth/AuthConfirm.js#L87

Once the onboarding flow gets fixed, users won't be end up at that stage. In that case, the final 'Welcome back" state is more like a redundancy/safety net for if a user somehow ends up on that stage and wasn't redirected already. I can still remove it if we don't want it

2023-04-17 18:53 UTC, jordanwade commented
@linb1 I'm good with the redundancy/safety net 👍

2023-04-17 18:54 UTC, jordanwade approved these changes

2023-04-17 18:54 UTC, merged